name: nextmit_app
description: "Application d'événementiel pour le festival Eat & Drink"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.1.0
  crypto: ^3.0.3
  flutter_image_compress: ^2.1.0
  collection: ^1.17.2
  retry: ^3.1.2
  cached_network_image: ^3.3.0
  web_socket_channel: ^2.4.0
  fl_chart: ^0.65.0
  data_table_2: ^2.5.8
  intl: ^0.18.1
  flutter_quill: ^8.4.3
  flutter_datetime_picker_plus: ^2.1.0
  flutter_slidable: ^3.0.1
  # firebase_storage: 11.5.6
  # firebase_storage_web: 3.6.17
  js: ^0.6.7
  firebase_core: ^2.27.1
  firebase_core_web: ^2.10.0
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
